<div class="col-md-12">
	<div class="page-margin mt-0 wow_content profile-completion-bar bar-<?php echo array_sum($wo['pr_complition']);?>" data-profile-completion="<?php echo array_sum($wo['pr_complition']); ?>">
		
	<?php
				if(!empty($wo['pr_complition'][1]) && $wo['pr_complition'][2] && $wo['pr_complition'][3] && $wo['pr_complition'][4] && $wo['pr_complition'][5] && $wo['user']['verified']){
			?>
				<h3>
				<span class="verified-color"> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="feather feather-check-circle" title="" data-toggle="tooltip" data-original-title="Verified User"> <path d="M23,12L20.56,9.22L20.9,5.54L17.29,4.72L15.4,1.54L12,3L8.6,1.54L6.71,4.72L3.1,5.53L3.44,9.21L1,12L3.44,14.78L3.1,18.47L6.71,19.29L8.6,22.47L12,21L15.4,22.46L17.29,19.28L20.9,18.46L20.56,14.78L23,12M10,17L6,13L7.41,11.59L10,14.17L16.59,7.58L18,9L10,17Z"></path> </svg> </span>
				Yipee You're verified</h3>

				<?php }else{ ?>


	<div class="hdr">
			<div class="progresss"></div>
			&nbsp;&nbsp;&nbsp;&nbsp;
			<h3><?php echo $wo['lang']['pr_completion']; ?></h3>
		</div>
		
		<div class="body">




			<?php if (empty($wo['pr_complition'][1])): ?>
				<div class="step" id="add-profile-avatar">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M17,13H13V17H11V13H7V11H11V7H13V11H17M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z" /></svg>&nbsp;&nbsp;<?php echo $wo['lang']['ad_pr_picture']; ?>   
				</div>
			<?php else: ?>
				<div class="step done">
				   <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#42a846" d="M12 2C6.5 2 2 6.5 2 12S6.5 22 12 22 22 17.5 22 12 17.5 2 12 2M10 17L5 12L6.41 10.59L10 14.17L17.59 6.58L19 8L10 17Z" /></svg>&nbsp;&nbsp;<?php echo $wo['lang']['ad_pr_picture']; ?>
				</div>
			<?php endif; ?>

			<?php if (!empty($wo['pr_complition'][2])): ?>
				<div class="step done">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#42a846" d="M12 2C6.5 2 2 6.5 2 12S6.5 22 12 22 22 17.5 22 12 17.5 2 12 2M10 17L5 12L6.41 10.59L10 14.17L17.59 6.58L19 8L10 17Z" /></svg>&nbsp;&nbsp;<?php echo $wo['lang']['add_ur_name']; ?>
				</div>
			<?php else: ?>
				<a class="step" href="<?php echo Wo_SeoLink('index.php?link1=setting&page=profile-setting');?>" data-ajax="?link1=setting&page=profile-setting">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M17,13H13V17H11V13H7V11H11V7H13V11H17M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z" /></svg>&nbsp;&nbsp;<?php echo $wo['lang']['add_ur_name']; ?>
				</a>
			<?php endif; ?>

			<?php if (!empty($wo['pr_complition'][3])): ?>
				<div class="step done">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#42a846" d="M12 2C6.5 2 2 6.5 2 12S6.5 22 12 22 22 17.5 22 12 17.5 2 12 2M10 17L5 12L6.41 10.59L10 14.17L17.59 6.58L19 8L10 17Z" /></svg>&nbsp;&nbsp;<?php echo $wo['lang']['ad_ur_workplace']; ?>
				</div>
			<?php else: ?>
				<a class="step" href="<?php echo Wo_SeoLink('index.php?link1=setting&page=profile-setting');?>" data-ajax="?link1=setting&page=profile-setting">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M17,13H13V17H11V13H7V11H11V7H13V11H17M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z" /></svg>&nbsp;&nbsp;<?php echo $wo['lang']['ad_ur_workplace']; ?>
				</a> 
			<?php endif; ?>

			<?php if (!empty($wo['pr_complition'][4])): ?>
				<div class="step done">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#42a846" d="M12 2C6.5 2 2 6.5 2 12S6.5 22 12 22 22 17.5 22 12 17.5 2 12 2M10 17L5 12L6.41 10.59L10 14.17L17.59 6.58L19 8L10 17Z" /></svg>&nbsp;&nbsp;<?php echo $wo['lang']['ad_ur_country']; ?>
				</div>
			<?php else: ?>
				<a class="step" href="<?php echo Wo_SeoLink('index.php?link1=setting&page=general-setting');?>" data-ajax="?link1=setting&page=general-setting">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M17,13H13V17H11V13H7V11H11V7H13V11H17M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z" /></svg>&nbsp;&nbsp;<?php echo $wo['lang']['ad_ur_country']; ?>
				</a>
			<?php endif; ?>

			<?php if (!empty($wo['pr_complition'][5])): ?>
				<div class="step done">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#42a846" d="M12 2C6.5 2 2 6.5 2 12S6.5 22 12 22 22 17.5 22 12 17.5 2 12 2M10 17L5 12L6.41 10.59L10 14.17L17.59 6.58L19 8L10 17Z" /></svg>&nbsp;&nbsp;<?php echo $wo['lang']['ad_ur_address']; ?>
				</div>
			<?php else: ?>
				<a class="step" href="<?php echo Wo_SeoLink('index.php?link1=setting&page=profile-setting');?>" data-ajax="?link1=setting&page=profile-setting">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M17,13H13V17H11V13H7V11H11V7H13V11H17M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z" /></svg>&nbsp;&nbsp;<?php echo $wo['lang']['ad_ur_address']; ?>
				</a>
			<?php endif; ?>
			<?php if ($wo['user']['verified']): ?>
				<div class="step done">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#42a846" d="M12 2C6.5 2 2 6.5 2 12S6.5 22 12 22 22 17.5 22 12 17.5 2 12 2M10 17L5 12L6.41 10.59L10 14.17L17.59 6.58L19 8L10 17Z" /></svg>&nbsp;&nbsp;Upload a Voters Card / Drivers License
				</div>
			<?php else: ?>
				<a class="step" href="<?php echo Wo_SeoLink('index.php?link1=setting&page=verification');?>" data-ajax="?link1=setting&page=verification">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M17,13H13V17H11V13H7V11H11V7H13V11H17M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z" /></svg>&nbsp;&nbsp;Upload a Voters Card / Drivers License to get verified
				</a>
			<?php endif; ?>
		</div>
		<?php } ?>

	</div>

	

	<script>
	jQuery(document).ready(function($) {
		$("#add-profile-avatar").click(function(event) {
			$('.profile-avatar-changer').find('input').trigger('click');
		});
	});

	new CircleProgress('.progresss', {
		max: 100,
		value: <?php echo array_sum($wo['pr_complition']); ?>,
		textFormat: 'percent',
	});
	</script>
</div>